import type { PlanetCatalogEntry } from './schema'

// Non-home base + PoK planets. Sourced from AsyncTI4 per-planet data
// (src/main/resources/planets/*.json), res/inf/trait/techSpecialty verified.
// Legendary ability summaries are authored (our words), not verbatim card text.
export const planets: PlanetCatalogEntry[] = [
  // ---------- Base game (33, incl. Mecatol Rex) ----------
  { id: 'abyz', name: 'Abyz', resources: 3, influence: 0, trait: 'hazardous', legendary: false, expansion: 'base' },
  { id: 'arinam', name: 'Arinam', resources: 1, influence: 2, trait: 'industrial', legendary: false, expansion: 'base' },
  { id: 'arnor', name: 'Arnor', resources: 2, influence: 1, trait: 'industrial', legendary: false, expansion: 'base' },
  { id: 'bereg', name: 'Bereg', resources: 3, influence: 1, trait: 'hazardous', legendary: false, expansion: 'base' },
  { id: 'centauri', name: 'Centauri', resources: 1, influence: 3, trait: 'cultural', legendary: false, expansion: 'base' },
  { id: 'corneeq', name: 'Corneeq', resources: 1, influence: 2, trait: 'cultural', legendary: false, expansion: 'base' },
  { id: 'dalbootha', name: 'Dal Bootha', resources: 0, influence: 2, trait: 'cultural', legendary: false, expansion: 'base' },
  { id: 'fria', name: 'Fria', resources: 2, influence: 0, trait: 'hazardous', legendary: false, expansion: 'base' },
  { id: 'gral', name: 'Gral', resources: 1, influence: 1, trait: 'industrial', techSpecialty: 'blue', legendary: false, expansion: 'base' },
  { id: 'lazar', name: 'Lazar', resources: 1, influence: 0, trait: 'industrial', techSpecialty: 'yellow', legendary: false, expansion: 'base' },
  { id: 'lirtaiv', name: 'Lirta IV', resources: 2, influence: 3, trait: 'hazardous', legendary: false, expansion: 'base' },
  { id: 'lodor', name: 'Lodor', resources: 3, influence: 1, trait: 'cultural', legendary: false, expansion: 'base' },
  { id: 'lor', name: 'Lor', resources: 1, influence: 2, trait: 'industrial', legendary: false, expansion: 'base' },
  { id: 'mr', name: 'Mecatol Rex', resources: 1, influence: 6, legendary: false, expansion: 'base' },
  { id: 'meer', name: 'Meer', resources: 0, influence: 4, trait: 'hazardous', techSpecialty: 'red', legendary: false, expansion: 'base' },
  { id: 'meharxull', name: 'Mehar Xull', resources: 1, influence: 3, trait: 'hazardous', techSpecialty: 'red', legendary: false, expansion: 'base' },
  { id: 'mellon', name: 'Mellon', resources: 0, influence: 2, trait: 'cultural', legendary: false, expansion: 'base' },
  { id: 'newalbion', name: 'New Albion', resources: 1, influence: 1, trait: 'industrial', techSpecialty: 'green', legendary: false, expansion: 'base' },
  { id: 'quann', name: 'Quann', resources: 2, influence: 1, trait: 'cultural', legendary: false, expansion: 'base' },
  { id: 'qucenn', name: 'Qucen\'n', resources: 1, influence: 2, trait: 'industrial', legendary: false, expansion: 'base' },
  { id: 'rarron', name: 'Rarron', resources: 0, influence: 3, trait: 'cultural', legendary: false, expansion: 'base' },
  { id: 'resculon', name: 'Resculon', resources: 2, influence: 0, trait: 'cultural', legendary: false, expansion: 'base' },
  { id: 'sakulag', name: 'Sakulag', resources: 2, influence: 1, trait: 'hazardous', legendary: false, expansion: 'base' },
  { id: 'saudor', name: 'Saudor', resources: 2, influence: 2, trait: 'industrial', legendary: false, expansion: 'base' },
  { id: 'starpoint', name: 'Starpoint', resources: 3, influence: 1, trait: 'hazardous', legendary: false, expansion: 'base' },
  { id: 'tarmann', name: 'Tar\'mann', resources: 1, influence: 1, trait: 'industrial', techSpecialty: 'green', legendary: false, expansion: 'base' },
  { id: 'tequran', name: 'Tequ\'ran', resources: 2, influence: 0, trait: 'hazardous', legendary: false, expansion: 'base' },
  { id: 'thibah', name: 'Thibah', resources: 1, influence: 1, trait: 'industrial', techSpecialty: 'blue', legendary: false, expansion: 'base' },
  { id: 'torkan', name: 'Torkan', resources: 0, influence: 3, trait: 'cultural', legendary: false, expansion: 'base' },
  { id: 'vefutii', name: 'Vefut II', resources: 2, influence: 2, trait: 'hazardous', legendary: false, expansion: 'base' },
  { id: 'wellon', name: 'Wellon', resources: 1, influence: 2, trait: 'industrial', techSpecialty: 'yellow', legendary: false, expansion: 'base' },
  { id: 'xxehan', name: 'Xxehan', resources: 1, influence: 1, trait: 'cultural', legendary: false, expansion: 'base' },
  { id: 'zohbat', name: 'Zohbat', resources: 3, influence: 1, trait: 'hazardous', legendary: false, expansion: 'base' },
  // ---------- Prophecy of Kings (30) ----------
  { id: 'abaddon', name: 'Abaddon', resources: 1, influence: 0, trait: 'cultural', legendary: false, expansion: 'pok' },
  { id: 'accoen', name: 'Accoen', resources: 2, influence: 3, trait: 'industrial', legendary: false, expansion: 'pok' },
  { id: 'alioprima', name: 'Alio Prima', resources: 1, influence: 1, trait: 'cultural', legendary: false, expansion: 'pok' },
  { id: 'ang', name: 'Ang', resources: 2, influence: 0, trait: 'industrial', techSpecialty: 'red', legendary: false, expansion: 'pok' },
  { id: 'archonvail', name: 'Archon Vail', resources: 1, influence: 3, trait: 'hazardous', techSpecialty: 'blue', legendary: false, expansion: 'pok' },
  { id: 'ashtroth', name: 'Ashtroth', resources: 2, influence: 0, trait: 'hazardous', legendary: false, expansion: 'pok' },
  { id: 'atlas', name: 'Atlas', resources: 3, influence: 1, trait: 'hazardous', legendary: false, expansion: 'pok' },
  { id: 'bakal', name: 'Bakal', resources: 3, influence: 2, trait: 'industrial', legendary: false, expansion: 'pok' },
  { id: 'cealdri', name: 'Cealdri', resources: 0, influence: 2, trait: 'cultural', techSpecialty: 'yellow', legendary: false, expansion: 'pok' },
  { id: 'cormund', name: 'Cormund', resources: 2, influence: 0, trait: 'hazardous', legendary: false, expansion: 'pok' },
  { id: 'everra', name: 'Everra', resources: 3, influence: 1, trait: 'cultural', legendary: false, expansion: 'pok' },
  { id: 'hopesend', name: 'Hope\'s End', resources: 3, influence: 0, trait: 'hazardous', legendary: true, legendaryAbility: 'Exhaust at the end of your turn to place 1 mech on a planet you control, or draw 1 action card.', expansion: 'pok' },
  { id: 'jeolir', name: 'Jeol Ir', resources: 2, influence: 3, trait: 'industrial', legendary: false, expansion: 'pok' },
  { id: 'kraag', name: 'Kraag', resources: 2, influence: 1, trait: 'hazardous', legendary: false, expansion: 'pok' },
  { id: 'lisis', name: 'Lisis', resources: 2, influence: 2, trait: 'industrial', legendary: false, expansion: 'pok' },
  { id: 'loki', name: 'Loki', resources: 1, influence: 2, trait: 'cultural', legendary: false, expansion: 'pok' },
  { id: 'mallice', name: 'Mallice', resources: 0, influence: 3, trait: 'cultural', legendary: true, legendaryAbility: 'Exhaust at the end of your turn to gain 2 trade goods, or convert all your commodities to trade goods.', expansion: 'pok' },
  { id: 'mirage', name: 'Mirage', resources: 1, influence: 2, trait: 'cultural', legendary: true, legendaryAbility: 'Exhaust at the end of your turn to place up to 2 fighters in any system that contains your ships.', expansion: 'pok' },
  { id: 'perimeter', name: 'Perimeter', resources: 2, influence: 1, trait: 'industrial', legendary: false, expansion: 'pok' },
  { id: 'primor', name: 'Primor', resources: 2, influence: 1, trait: 'cultural', legendary: true, legendaryAbility: 'Exhaust at the end of your turn to place up to 2 infantry on any planet you control.', expansion: 'pok' },
  { id: 'rigeli', name: 'Rigel I', resources: 0, influence: 1, trait: 'hazardous', legendary: false, expansion: 'pok' },
  { id: 'rigelii', name: 'Rigel II', resources: 1, influence: 2, trait: 'industrial', legendary: false, expansion: 'pok' },
  { id: 'rigeliii', name: 'Rigel III', resources: 1, influence: 1, trait: 'industrial', techSpecialty: 'green', legendary: false, expansion: 'pok' },
  { id: 'semlore', name: 'Sem-Lore', resources: 3, influence: 2, trait: 'cultural', techSpecialty: 'yellow', legendary: false, expansion: 'pok' },
  { id: 'siig', name: 'Siig', resources: 0, influence: 2, trait: 'hazardous', legendary: false, expansion: 'pok' },
  { id: 'vegamajor', name: 'Vega Major', resources: 2, influence: 1, trait: 'cultural', legendary: false, expansion: 'pok' },
  { id: 'vegaminor', name: 'Vega Minor', resources: 1, influence: 2, trait: 'cultural', techSpecialty: 'blue', legendary: false, expansion: 'pok' },
  { id: 'velnor', name: 'Velnor', resources: 2, influence: 1, trait: 'industrial', techSpecialty: 'red', legendary: false, expansion: 'pok' },
  { id: 'vorhal', name: 'Vorhal', resources: 0, influence: 2, trait: 'cultural', techSpecialty: 'green', legendary: false, expansion: 'pok' },
  { id: 'xanhact', name: 'Xanhact', resources: 0, influence: 1, trait: 'hazardous', legendary: false, expansion: 'pok' },
]
